apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: extractor
  template:
    metadata:
      labels:
        app: extractor
    spec:
      containers:
        - image: cheapacr.azurecr.io/extractor:186b29282f57038699b84909d1bac5e2de237774
          name: extractor
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
